version: "3.9"
services:
  api:
    build: ./backend
    command: uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000
    volumes: [ "./backend:/app/backend" ]
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on: [ redis ]
    ports: [ "8000:8000" ]

  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]
